server:
  port: 8081
spring:
  application:
    name: comment_demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: lyh59439
  redis:
    host: 127.0.0.1
    port: 6379
    password: lyh123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.woshimax.shop_finder.entity # 别名扫描包
logging:
  level:
    com.woshimax.shop_finder: debug