---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by yuheng.
--- DateTime: 2024/5/7 13:19
---

-- 1、优惠券id和用户id传入——value
-- 改进阻塞队列为用redis的stream实现消息队列，直接传入订单信息
local voucherId = ARGV[1]
local userId = ARGV[2]
local orderId = ARGV[3]

--2、库存key和订单key(lua脚本字符串拼接用..)
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId

--3.1判读库存——防止超卖
if(tonumber(redis.call('get',stockKey)) <= 0)
    --库存不足返回1
    then return 1
end
--3.2判断用户是否购买过——保证一人一单（使用redis的set来判读）
if(redis.call('sismember',orderKey,userId) == 1)
    --如果存在返回2（重复下单）
    then return 2
end

--如果都满足，扣减库存，存入用户
redis.call('incrby',stockKey,-1)
redis.call('sadd',orderKey,userId)
--判断完资格之后发消息到队列中('*'就是不指定消费者，redis自动生成
redis.call('xadd','stream.orders','*','userId',userId,'voucherId',voucherId,'id',orderId)
--要有返回值！！没问题一般返回0
return 0